bin/civi-download-tools - Add option to download full system
Ex: curl http://...civi-downlad-tools | bash -s -- --full --dir ~/buildkit

diff --git a/bin/civi-download-tools b/bin/civi-download-tools
--- a/bin/civi-download-tools
+++ b/bin/civi-download-tools
@@ -15,7 +15,6 @@ function absdirname() {
 
 BINDIR=$(absdirname "$0")
 PRJDIR=$(dirname "$BINDIR")
-WEBDIR="$PRJDIR/web"
 TMPDIR="$PRJDIR/app/tmp"
 LOCKFILE="$TMPDIR/civi-download-tools.lock"
 LOCKTIMEOUT=90
@@ -25,10 +24,52 @@ HUBTAG="v1.12.4"
 HUBURL="https://github.com/github/hub"
 IS_QUIET=
 IS_FORCE=
+IS_FULL=
 
 ##################################################
-## Helpers
+## Parse arguments
+while [ -n "$1" ] ; do
+  OPTION="$1"
+  shift
 
+  case "$OPTION" in
+    -q|--quiet)
+      ## Don't display advisory comments
+      ## Only display messages if we're actually making changes
+      IS_QUIET=1
+      ;;
+
+    -f|--force)
+      ## (Re)-download everything
+      IS_FORCE=1
+      ;;
+
+    --full)
+      ## Heuristically identify/download system packages.
+      IS_FULL=1
+      ;;
+
+    --dir)
+      set -e
+        [ ! -d "$1" ] && mkdir "$1"
+        pushd "$1" >> /dev/null
+          PRJDIR=$(pwd)
+        popd >> /dev/null
+        BINDIR="$PRJDIR/bin"
+        TMPDIR="$PRJDIR/app/tmp"
+        LOCKFILE="$TMPDIR/civi-download-tools.lock"
+      set +e
+      shift
+      ;;
+
+    *)
+      echo "Unrecognized option: $OPTION"
+      echo "Usage: $0 [-q|--quiet] [-f|--force] [--full] [--dir <path>]"
+      ;;
+  esac
+done
+
+###############################################################################
 ## usage: download_url <url> <out-file>
 function download_url() {
   #php -r "echo file_get_contents('$1');" > $2
@@ -41,6 +82,7 @@ function download_url() {
   fi
 }
 
+###############################################################################
 ## usage: echo_comment <message>
 function echo_comment() {
   if [ -z "$IS_QUIET" ]; then
@@ -48,6 +90,7 @@ function echo_comment() {
   fi
 }
 
+###############################################################################
 ## Ensure that a command is on the PATH. If missing, then give
 ## advice on possible resolutions and exit.
 ## usage: check_command <command-name> <required|recommended> [<msg>]
@@ -84,6 +127,7 @@ function check_command() {
   fi
 }
 
+###############################################################################
 ## Debian.org's NodeJS package uses a non-standard name for the node binary.
 ## If necessary, setup an alias for the standard name.
 function nodejs_debian_workaround() {
@@ -95,6 +139,7 @@ function nodejs_debian_workaround() {
   fi
 }
 
+###############################################################################
 ## Check if a PHP extension is enabled
 ## usage: check_php_ext <command-name> <required|recommended> [<msg>]
 ##
@@ -120,32 +165,100 @@ function check_php_ext() {
   fi
 }
 
-##################################################
-## Parse arguments
-while [ -n "$1" ] ; do
-  OPTION="$1"
-  shift
-
-  case "$OPTION" in
-    -q|--quiet)
-      ## Don't display advisory comments
-      ## Only display messages if we're actually making changes
-      IS_QUIET=1
-      shift
+###############################################################################
+## Prompt user for confirmation
+## (In automated scripts or blank response, use default)
+##
+## usage: cvutil_confirm <message> <interactive-default> <script-default>
+## example: cvutil_confirm "Are you sure? [Y/n] " y y
+function cvutil_confirm() {
+  local msg="$1"
+  local i_default="$2"
+  local s_default="$3"
+  if tty -s ; then
+    echo -n "$msg"
+    read _cvutil_confirm
+    if [ "x$_cvutil_confirm" == "x" ]; then
+      _cvutil_confirm="$i_default"
+    fi
+  else
+    echo "${msg}${s_default}"
+    _cvutil_confirm="$s_default"
+  fi
+  case "$_cvutil_confirm" in
+    y|Y|1)
+      return 0
       ;;
-
-    -f|--force)
-      ## (Re)-download everything
-      IS_FORCE=1
-      shift
-      ;;
-
     *)
-      echo "Unrecognized option: $OPTION"
-      civibuild_usage
+      return 1
       ;;
   esac
-done
+}
+
+###############################################################################
+## Determine the function to handle system package installation
+function get_system_installer() {
+  if [ -f "/etc/lsb-release" ]; then
+    source /etc/lsb-release
+    case "$DISTRIB_CODENAME" in
+      trusty)
+        echo "do_system_$DISTRIB_CODENAME"
+        return
+    esac
+  fi
+  echo do_system_unknown
+}
+
+###############################################################################
+function do_system_trusty() {
+  set -e
+    PACKAGES="acl git wget unzip mysql-server mysql-client php5-cli php5-imap php5-ldap php5-curl php5-mysql php5-intl php5-gd php5-mcrypt php-apc apache2 libapache2-mod-php5 nodejs-legacy npm ruby rake"
+    echo "Detected \"Ubuntu Trusty\"."
+    echo ""
+    echo "Recommended packages: $PACKAGES"
+    echo ""
+    if cvutil_confirm "Run automated installation? [Y/n] " y y; then
+      sudo apt-get install $PACKAGES
+      sudo php5enmod mcrypt
+      sudo php5enmod imap
+      sudo a2enmod rewrite
+      sudo apache2ctl restart
+    else
+      echo "Aborted" 1>&2
+      exit 1
+    fi
+  set +e
+}
+
+###############################################################################
+function do_system_unknown() {
+  echo "ERROR: Could not identify the required system packages."
+  echo ""
+  echo "If you want to add support for a new system, update 'get_system_installer()'"
+  echo "and add a new 'do_system_*()' function."
+  exit 1
+}
+
+
+
+##################################################
+## Perform system installation (if requested)
+if [ -n "$IS_FULL" ]; then
+  SYSTEM_FUNC=$(get_system_installer)
+  if [[ $SYSTEM_FUNC =~ ^[a-zA-Z0-9_]+$ ]]; then
+    $SYSTEM_FUNC
+  else
+    echo "ERROR: Malformed system function: $SYSTEM_FUNC"
+    exit 2
+  fi
+
+  if [ ! -f "$PRJDIR/composer.json" ]; then
+    set -e
+      echo "[[ Clone civicrm-buildkit to $PRJDIR ]]"
+      git clone "https://github.com/civicrm/civicrm-buildkit.git" "$PRJDIR"
+    set +e
+  fi
+fi
 
 ##################################################
 ## Validation
