civibuild - Refine confirmations

diff --git a/bin/civibuild b/bin/civibuild
--- a/bin/civibuild
+++ b/bin/civibuild
@@ -123,7 +123,7 @@ function civibuild_download() {
   echo "[[Download $SITE_NAME (type '$SITE_TYPE' in '$WEB_ROOT')]]"
 
   if [ -n "$FORCE_DOWNLOAD" -a -d "$WEB_ROOT" ]; then
-    if cvutil_confirm "Are you sure you want destroy \"$WEB_ROOT\"? [n/Y] " n y; then
+    if cvutil_confirm "About to re-download \"$WEB_ROOT\". Are you sure you want destroy existing files? [y/N] " n y; then
       rm -rf "$WEB_ROOT"
     else
       echo "Aborted" 1>&2
@@ -163,13 +163,17 @@ function civibuild_install() {
   fi
 
   if [ -n "$FORCE_INSTALL" -a -n "$IS_INSTALLED" ]; then
-    if cvutil_confirm "Are you sure you want destroy \"$WEB_ROOT\"? [y/N] " n y; then
+
+    if cvutil_confirm "About to re-install \"$WEB_ROOT\". Are you sure you want destroy existing data? [y/N] " n y; then
       pushd "$WEB_ROOT" > /dev/null
         civibuild_run uninstall
       popd > /dev/null
       if [ -d "$PRIVATE_ROOT" ]; then
         rm -rf "$PRIVATE_ROOT"
       fi
+    else
+      echo "Aborted" 1>&2
+      exit 1
     fi
   fi
 
@@ -427,6 +431,9 @@ case "$ACTION" in
         [ -f "$f" ] && rm -f "$f"
       done
       amp cleanup
+    else
+      echo "Aborted" 1>&2
+      exit 1
     fi
     ;;
 
