bin/cividist - Use standard version numbers, but rename files to superficially indicate build-date.

diff --git a/bin/cividist b/bin/cividist
--- a/bin/cividist
+++ b/bin/cividist
@@ -12,6 +12,7 @@ TARS=${TARS:-$PRJ/out/tar}
 BY_DATE=${BY_DATE:-$PRJ/web/by-date}
 BY_HASH=${BY_HASH:-$PRJ/web/by-hash}
 DATE=$( date '+%Y-%m-%d' )
+FILE_SUFFIX=$( date '+%Y%m%d' )
 ## #minutes before redownloading L10n (12*60=720 min)
 L10N_TTL=720
 L10N_URL=http://download.civicrm.org/civicrm-l10n-core/archives/civicrm-l10n-daily.tar.gz
@@ -67,14 +68,7 @@ function cividist_build() {
         echo "[$DATE $REF] Found hash $hash" 1>&2
       else
         echo "[$DATE $REF] Building hash $hash]" 1>&2
-        mkdir "$BY_HASH/$hash"
-        pushd distmaker >> /dev/null
-          if env DM_TARGETDIR="$BY_HASH/$hash" DM_REF_CORE="$REF" DM_VERSION_SUFFIX="-$DATE" ./distmaker.sh all ; then
-            echo "[$DATE $REF] Built hash $hash" 1>&2
-          else
-            echo "[$DATE $REF] Build failed for hash $hash" 1>&2
-          fi
-        popd >> /dev/null
+        _cividist_build_hash "$hash"
       fi
 
       if [ -d "$BY_DATE/$DATE/$refname" ]; then
@@ -92,6 +86,35 @@ function cividist_build() {
   ## Update "latest" symlink
   [ -L "$BY_DATE/latest" ] && rm -f "$BY_DATE/latest"
   [ ! -e "$BY_DATE/latest" ] && ln -s "$BY_DATE/$DATE" "$BY_DATE/latest"
+}
+
+###############################################################################
+## usage: _cividist_build_hash <hash>
+## depends: BY_HASH, DATE, REF, FILE_SUFFIX
+function _cividist_build_hash() {
+  local hash="$1"
+  local hashtmp="$BY_HASH/$hash.tmp"
+  local hashout="$BY_HASH/$hash"
+
+  mkdir -p "$hashtmp"
+  mkdir -p "$hashout"
+  pushd distmaker >> /dev/null
+    if env DM_TARGETDIR="$hashtmp" DM_REF_CORE="$REF" DM_VERSION_SUFFIX= ./distmaker.sh all ; then
+      echo "[$DATE $REF] Built hash $hash" 1>&2
+      pushd "$hashtmp" >> /dev/null
+        regmv '\.zip$' "-${FILE_SUFFIX}.zip"
+        regmv '\.tgz$' "-${FILE_SUFFIX}.tgz"
+        regmv '\.tar\.gz$' "-${FILE_SUFFIX}.tar.gz"
+      popd >> /dev/null
+      mv "$hashtmp"/* "$hashout/"
+    else
+      echo "[$DATE $REF] Build failed for hash $hash" 1>&2
+    fi
+
+    if [ -d "$hashtmp" ]; then
+      rm -rf "$hashtmp"
+    fi
+  popd >> /dev/null
 }
 
 ###############################################################################
