civi-test-run - Separate the parsing/validation/execution. Fix help on blank.
When calling `civi-test-run` without any arguments, it crashed because
several variables were undefined.

Now:
 * All the arguments are parsed before doing any validation.
 * All the arguments are parsed and validated before doing any execution.
 * It doesn't matter what order you pass the arguments.
 * If you forget to pass an argument, it displays a help screen.

diff --git a/bin/civi-test-run b/bin/civi-test-run
--- a/bin/civi-test-run
+++ b/bin/civi-test-run
@@ -110,6 +110,7 @@ function absdirname() {
 BINDIR=$(absdirname "$0")
 PRJDIR=$(dirname "$BINDIR")
 EXITCODES=
+SUITES=
 GUARD=
 
 #################################################
@@ -159,10 +160,22 @@ while [ -n "$1" ] ; do
     exit 2
 
   else
-    TESTTYPE="$1"
-    run_tests
+    SUITES="$SUITES $1"
     shift
   fi
+done
+
+## Validate
+if [ -z "$SUITES" -o -z "$BLDNAME" -o -z "$JUNITDIR" ]; then
+  echo "Error: Missing required argument"
+  echo
+  show_help
+  exit 2
+fi
+
+## Main
+for TESTTYPE in $SUITES ; do
+  run_tests
 done
 
 ## Check test results and set exit code
