civibuild - When used interactively, confirm destructions

diff --git a/bin/civibuild b/bin/civibuild
--- a/bin/civibuild
+++ b/bin/civibuild
@@ -123,7 +123,12 @@ function civibuild_download() {
   echo "[[Download $SITE_NAME (type '$SITE_TYPE' in '$WEB_ROOT')]]"
 
   if [ -n "$FORCE_DOWNLOAD" -a -d "$WEB_ROOT" ]; then
-    rm -rf "$WEB_ROOT"
+    if cvutil_confirm "Are you sure you want destroy \"$WEB_ROOT\"? [n/Y] " n y; then
+      rm -rf "$WEB_ROOT"
+    else
+      echo "Aborted" 1>&2
+      exit 1
+    fi
   fi
 
   if [ ! -d "$WEB_ROOT" ]; then
@@ -158,11 +163,13 @@ function civibuild_install() {
   fi
 
   if [ -n "$FORCE_INSTALL" -a -n "$IS_INSTALLED" ]; then
-    pushd "$WEB_ROOT" > /dev/null
-      civibuild_run uninstall
-    popd > /dev/null
-    if [ -d "$PRIVATE_ROOT" ]; then
-      rm -rf "$PRIVATE_ROOT"
+    if cvutil_confirm "Are you sure you want destroy \"$WEB_ROOT\"? [y/N] " n y; then
+      pushd "$WEB_ROOT" > /dev/null
+        civibuild_run uninstall
+      popd > /dev/null
+      if [ -d "$PRIVATE_ROOT" ]; then
+        rm -rf "$PRIVATE_ROOT"
+      fi
     fi
   fi
 
@@ -413,12 +420,14 @@ case "$ACTION" in
     ;;
 
   destroy)
-    [ -d "$WEB_ROOT" ] && rm -rf "$WEB_ROOT"
-    [ -d "$PRIVATE_ROOT" ] && rm -rf "$PRIVATE_ROOT"
-    for f in "${BLDDIR}/${SITE_NAME}.sh" "${BLDDIR}/${SITE_NAME}".*.sh ; do
-      [ -f "$f" ] && rm -f "$f"
-    done
-    amp cleanup
+    if cvutil_confirm "Are you sure you want destroy \"$WEB_ROOT\"? [y/N] " n y; then
+      [ -d "$WEB_ROOT" ] && rm -rf "$WEB_ROOT"
+      [ -d "$PRIVATE_ROOT" ] && rm -rf "$PRIVATE_ROOT"
+      for f in "${BLDDIR}/${SITE_NAME}.sh" "${BLDDIR}/${SITE_NAME}".*.sh ; do
+        [ -f "$f" ] && rm -f "$f"
+      done
+      amp cleanup
+    fi
     ;;
 
   download|dl)
