use-bknix - Add option to load .loco/worker-n.yml

diff --git a/nix/bin/use-bknix b/nix/bin/use-bknix
--- a/nix/bin/use-bknix
+++ b/nix/bin/use-bknix
@@ -33,44 +33,62 @@ TXT_WHITE='\[\033[0;37m\]'
 ## Input parsing
 
 MODE=env
+USE_LOCO_FILE=""
+PROFILE=
+RECURSE_OPT=
 
 if [ -z "$OWNER" ]; then
   OWNER=$USER
 fi
 
-PROFILE="$1"
-shift
+while [ -n "$1" ]; do
+  OPT="$1"
+  shift
 
-for BASEDIR in "/nix/var/nix/profiles/per-user/$OWNER" "/nix/var/nix/profiles" ;do
+  case "$OPT" in
+    old|min|dfl|max|edge) PROFILE="$OPT" ; ;;
+    -s|--shell) MODE=shell ; ;;
+    -e|--env) MODE=env ; ;;
+    -r|--run) MODE=run ; ;;
+    -N|--worker-n)
+      USE_LOCO_FILE=".loco/worker-n.yml"
+      RECURSE_OPT=--worker-n
+      if [ "x$EXECUTOR_NUMBER" = "x" ]; then
+        echo "Error: The --worker-n option requires EXECUTOR_NUMBER" 1>&2
+        exit 1
+      fi
+      ;;
+    *) echo "Unrecognized option: $OPT" ; exit 1 ; ;;
+  esac
+
+  if [ "$MODE" = "run" -a -n "$PROFILE" ]; then
+    ## The rest of the args are RUN_CMD.
+    break
+  fi
+done
+
+for BASEDIR in "/nix/var/nix/profiles/per-user/$OWNER" "/nix/var/nix/profiles" ; do
   PRFDIR="$BASEDIR/bknix-$PROFILE"
   if [ -d "$PRFDIR" ]; then
     break
   fi
 done
 
-if [ -n "$1" ]; then
-  case "$1" in
-    -s|--shell) MODE=shell ; ;;
-    -e|--env) MODE=env ; ;;
-    -r|--run) MODE=run ; ;;
-    *) MODE=env ; ;;
-  esac
-  shift
-else
-  MODE=env
-fi
+#echo "PARSED: PROFILE=$PROFILE MODE=$MODE USE_LOCO_FILE=$USE_LOCO_FILE PRFDIR=$PRFDIR" > /dev/stderr
+#exit 10
 
 ###########################################################
 ## Validation/help
 if [ -z "$PROFILE" -o ! -d "$PRFDIR" ]; then
   echo "The specified profile does not correspond to an actual profile"
   echo
-  echo "usage: $0 <profile> [-e|--env|-s|--shell|-r|--run] [runcmd]"
+  echo "usage: $0 <PROFILE> [-N|--worker-n] [-e|--env|-s|--shell|-r|--run] [RUN_CMD]"
   echo ""
   echo "options:"
-  echo "  -e|--env    Display environment variables for the profile"
-  echo "  -s|--shell  Open a subshell with the profile"
-  echo "  -r|--run    Run a command in a subshell"
+  echo "  -e|--env       Display environment variables for the profile"
+  echo "  -s|--shell     Open a subshell with the profile"
+  echo "  -r|--run       Run a command in a subshell"
+  echo "  -N|--worker-n  Allocate ports for a temporary worker #N"
   echo ""
   echo "example: Generate environment variables for \"dfl\" profile"
   echo "  $0 dfl"
@@ -86,10 +104,14 @@ fi
 ## Main
 
 export PATH="$PRFDIR/bin:$PATH"
-USE_LOCO_FILE=""
+# PATH="$HOME/src/loco/bin:$PATH"
 
 for CANDIDATE in "$HOME/bknix" "$HOME/bknix-$PROFILE" "$HOME/buildkit" "$HOME/buildkit-$PROFILE" ; do
-  if [ -f "$CANDIDATE/.loco/$OWNER-$PROFILE.yml" ]; then
+  if [ -n "$USE_LOCO_FILE" -a -f "$CANDIDATE/$USE_LOCO_FILE" ]; then
+    export BKIT="$CANDIDATE"
+    ## Keep USE_LOCO_FILE
+    break
+  elif [ -f "$CANDIDATE/.loco/$OWNER-$PROFILE.yml" ]; then
     export BKIT="$CANDIDATE"
     USE_LOCO_FILE=".loco/$OWNER-$PROFILE.yml"
     break
@@ -128,7 +150,7 @@ case "$MODE" in
     }
     trap cleanup_bashrc EXIT
 
-    "$0" "$PROFILE" --env > "$TMPFILE"
+    "$0" "$PROFILE" $RECURSE_OPT --env > "$TMPFILE"
     bash --rcfile "$TMPFILE" -i
     ;;
   run)
@@ -141,7 +163,7 @@ case "$MODE" in
     }
     trap cleanup_bashrc EXIT
 
-    "$0" "$PROFILE" --env > "$TMPFILE"
+    "$0" "$PROFILE" $RECURSE_OPT --env > "$TMPFILE"
     source "$TMPFILE"
     "$@"
     ;;
