use-bknix - Accept option `-c` to change dir
This is helpful when you want to call loco, e.g.

use-bknix min -cr loco status

diff --git a/nix/bin/use-bknix b/nix/bin/use-bknix
--- a/nix/bin/use-bknix
+++ b/nix/bin/use-bknix
@@ -33,6 +33,18 @@ TXT_WHITE='\[\033[0;37m\]'
 ###########################################################
 ## Input parsing
 
+function use_worker_n() {
+  USE_LOCO_FILE=".loco/worker-n.yml"
+  if [[ "x$1" != "x" ]]; then
+    export EXECUTOR_NUMBER="$1"
+  fi
+
+  if [[ "x$EXECUTOR_NUMBER" = "x" ]]; then
+    echo "Error: The --worker-n option requires EXECUTOR_NUMBER" 1>&2
+    exit 1
+  fi
+}
+
 MODE=env
 USE_LOCO_FILE=""
 PROFILE=
@@ -45,26 +57,28 @@ while [ -n "$1" ]; do
   OPT="$1"
   shift
 
-  case "$OPT" in
-    old|min|dfl|max|edge) PROFILE="$OPT" ; ;;
-    -s|--shell) MODE=shell ; ;;
-    -e|--env) MODE=env ; ;;
-    -r|--run) MODE=run ; ;;
-    -N|--worker-n)
-      USE_LOCO_FILE=".loco/worker-n.yml"
-      if [ "x$EXECUTOR_NUMBER" = "x" ]; then
-        echo "Error: The --worker-n option requires EXECUTOR_NUMBER" 1>&2
-        exit 1
-      fi
-      ;;
-    -N0) USE_LOCO_FILE=".loco/worker-n.yml" ; export EXECUTOR_NUMBER=0 ; ;;
-    -N1) USE_LOCO_FILE=".loco/worker-n.yml" ; export EXECUTOR_NUMBER=1 ; ;;
-    -N2) USE_LOCO_FILE=".loco/worker-n.yml" ; export EXECUTOR_NUMBER=2 ; ;;
-    -N3) USE_LOCO_FILE=".loco/worker-n.yml" ; export EXECUTOR_NUMBER=3 ; ;;
-    -N4) USE_LOCO_FILE=".loco/worker-n.yml" ; export EXECUTOR_NUMBER=4 ; ;;
-    -N5) USE_LOCO_FILE=".loco/worker-n.yml" ; export EXECUTOR_NUMBER=5 ; ;;
-    *) echo "Unrecognized option: $OPT" ; exit 1 ; ;;
-  esac
+  while [[ "$OPT" != "" ]]; do
+
+    case "$OPT" in
+      old|min|dfl|max|edge) PROFILE="$OPT" ; OPT="" ;;
+      --shell) MODE=shell     ; OPT="" ;;
+      --env) MODE=env         ; OPT="" ;;
+      --run) MODE=run         ; OPT="" ;;
+      --project-dir) USE_CD=1 ; OPT="" ;;
+      -s*) MODE=shell         ; OPT="-${OPT:2}" ;;
+      -e*) MODE=env           ; OPT="-${OPT:2}" ;;
+      -r*) MODE=run           ; OPT="-${OPT:2}" ;;
+      -c*) USE_CD=1           ; OPT="-${OPT:2}" ;;
+
+      -N0*|-N1*|-N2*|-N3*|-N4*|-N5*|-N6*) use_worker_n "${OPT:2:1}" ; OPT="-${OPT:3}" ;;
+      --worker-n) use_worker_n ; OPT="" ;;
+      -N*) use_worker_n ; OPT="-${OPT:2}" ;;
+
+      -) OPT="" ; ;;
+      *) echo "Unrecognized option: $OPT" ; exit 1 ; ;;
+    esac
+
+  done
 
   if [ "$MODE" = "run" -a -n "$PROFILE" ]; then
     ## The rest of the args are RUN_CMD.
@@ -73,11 +87,7 @@ while [ -n "$1" ]; do
 done
 
 if [ -e "/etc/bknix-ci/is-runner" ]; then
-  USE_LOCO_FILE=".loco/worker-n.yml"
-  if [ "x$EXECUTOR_NUMBER" = "x" ]; then
-    echo "Error: The \"/etc/bknix-ci/is-runner\" option requires EXECUTOR_NUMBER" 1>&2
-    exit 1
-  fi
+  use_worker_n
 fi
 
 for BASEDIR in "/nix/var/nix/profiles/per-user/$OWNER" "/nix/var/nix/profiles" ; do
@@ -87,7 +97,7 @@ for BASEDIR in "/nix/var/nix/profiles/per-user/$OWNER" "/nix/var/nix/profiles" ;
   fi
 done
 
-#echo "PARSED: PROFILE=$PROFILE MODE=$MODE USE_LOCO_FILE=$USE_LOCO_FILE PRFDIR=$PRFDIR" > /dev/stderr
+#echo "PARSED: PROFILE=$PROFILE MODE=$MODE USE_LOCO_FILE=$USE_LOCO_FILE PRFDIR=$PRFDIR USE_CD=$USE_CD" > /dev/stderr
 #exit 10
 
 ###########################################################
@@ -95,13 +105,14 @@ done
 if [ -z "$PROFILE" -o ! -d "$PRFDIR" ]; then
   echo "The specified profile does not correspond to an actual profile"
   echo
-  echo "usage: $0 <PROFILE> [-N|--worker-n] [-e|--env|-s|--shell|-r|--run] [RUN_CMD]"
+  echo "usage: $0 <PROFILE> [-N|--worker-n] [-c|--project-dir] [-e|--env|-s|--shell|-r|--run] [RUN_CMD]"
   echo ""
   echo "options:"
-  echo "  -e|--env       Display environment variables for the profile"
-  echo "  -s|--shell     Open a subshell with the profile"
-  echo "  -r|--run       Run a command in a subshell"
-  echo "  -N|--worker-n  Allocate ports for a temporary worker #N"
+  echo "  -e|--env           Display environment variables for the profile"
+  echo "  -s|--shell         Open a subshell with the profile"
+  echo "  -r|--run           Run a command in a subshell"
+  echo "  -N|--worker-n      Allocate ports for a temporary worker #N"
+  echo "  -c|--project-dir   Change working directory to project-root"
   echo ""
   echo "example: Generate environment variables for \"dfl\" profile"
   echo "  $0 dfl"
@@ -136,6 +147,9 @@ for CANDIDATE in "$HOME/bknix" "$HOME/bknix-$PROFILE" "$HOME/buildkit" "$HOME/bu
 done
 if [ ! -d "$BKIT" ]; then
   echo "WARNING: Could not find suitable BKIT in \"$HOME\" (eg \"bknix\", \"buildkit\", \"bknix-min\")" >&2
+fi
+if [ -n "$USE_CD" ]; then
+  cd "$BKIT"
 fi
 
 function createScript() {
