install-runner.sh - Set sticky option to always use 'worker-n' mode

diff --git a/nix/bin/use-bknix b/nix/bin/use-bknix
--- a/nix/bin/use-bknix
+++ b/nix/bin/use-bknix
@@ -71,6 +71,14 @@ while [ -n "$1" ]; do
   fi
 done
 
+if [ -e "/etc/bknix-ci/worker-n" ]; then
+  USE_LOCO_FILE=".loco/worker-n.yml"
+  if [ "x$EXECUTOR_NUMBER" = "x" ]; then
+    echo "Error: The \"/etc/bknix-ci/worker-n\" option requires EXECUTOR_NUMBER" 1>&2
+    exit 1
+  fi
+fi
+
 for BASEDIR in "/nix/var/nix/profiles/per-user/$OWNER" "/nix/var/nix/profiles" ; do
   PRFDIR="$BASEDIR/bknix-$PROFILE"
   if [ -d "$PRFDIR" ]; then
